import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import Footer from '../components/Footer'

export const metadata: Metadata = {
	title: 'ProductEYE',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className='h-full'>
			<body className='h-full flex flex-col'>
				<Header />
				<main className='flex-grow'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
